git:
  depth: 3
  quiet: yes

branches:
  except:
    - legacy
    - experimental

notifications:
  email: ewen.lebihan7@gmail.com

matrix:
  include:
    - language: node_js
      node_js:
        - 13.5.0

      cache:
        yarn: true
        directories:
          - node_modules

      install:
        - yarn install

      script:
        - yarn build
        - yarn test

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: python
      python:
        - 3.7
      
      before_install:
        - cd tests/e2e
        
      sudo: on
      install:
        - pip install poetry
        - poetry install
      
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start  
      
      script:
        - poetry run behave
